# Generated by Django 3.2.8 on 2021-12-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puruweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('age', models.DateTimeField()),
                ('relation', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(max_length=500)),
                ('mothertounge', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='image/personal')),
            ],
        ),
    ]
