# Generated by Django 3.2.10 on 2021-12-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puruweb', '0002_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='gallary')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
