# Generated by Django 3.2.10 on 2021-12-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puruweb', '0004_alter_gallary_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='personal',
        ),
    ]
